# Generated by Django 2.0.5 on 2018-07-23 22:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=200)),
                ('iso3c', models.CharField(help_text='Country ISO3c code', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VT', 'Valult'), ('UB', 'Uneven Bars'), ('BB', 'Balance Beam'), ('FX', 'Floor Exercise')], help_text='Event', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('name', models.CharField(help_text="Enter a gymnast's name", max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular gymnast across whole library', primary_key=True, serialize=False)),
                ('summary', models.TextField(help_text='Enter a brief description of the gymnats', max_length=1000, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoredata.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the meet', max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('gymnast', models.ManyToManyField(help_text='Gymnasts who competed at this meet', to='scoredata.Gymnast')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_day', models.CharField(blank=True, choices=[('QF', 'Qualifying'), ('TF', 'Team Final'), ('AA', 'All Around Final'), ('EF', 'Event Finals')], help_text='Day of the meet', max_length=5)),
                ('score', models.FloatField(help_text='Total Score', null=True)),
                ('d_score', models.FloatField(help_text='Difficulty Score', null=True)),
                ('score_num', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoredata.Event')),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoredata.Gymnast')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoredata.Meet')),
            ],
        ),
    ]
