# Generated by Django 2.0.5 on 2018-07-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
