# Generated by Django 2.0.5 on 2018-09-01 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=130, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(help_text='Text of the blog post goes here')),
                ('date', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoredata.Author')),
                ('related', models.ManyToManyField(blank=True, related_name='_post_related_+', to='scoredata.Post')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=130, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='event',
            name='junior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular gymnast across whole database', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='scoredata.Tag'),
        ),
    ]
