# Generated by Django 2.0.5 on 2018-09-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0002_auto_20180901_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
