# Generated by Django 2.0.5 on 2018-08-10 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0004_auto_20180810_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular meet across whole database', primary_key=True, serialize=False),
        ),
    ]
