# Generated by Django 2.0.5 on 2018-08-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0009_auto_20180821_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
