# Generated by Django 2.0.5 on 2018-08-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0010_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
