# Generated by Django 2.0.5 on 2018-08-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0011_auto_20180821_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, null=True),
        ),
    ]
