# Generated by Django 2.0.5 on 2018-08-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0012_auto_20180822_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_post_related_+', to='scoredata.Post'),
        ),
    ]
