# Generated by Django 2.0.5 on 2018-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0014_auto_20180831_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
