# Generated by Django 2.0.5 on 2018-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoredata', '0015_auto_20180831_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
